IcecreamShop

In [3]:
import numpy as np

In [4]:
menu = np.array([
    [2,10],
    [3,10],
    [4,10],
    [5,10],
    [6,10],
])

name = np.array(["Chocolate", "Vanila", "strawberry", "Orange", "Apple"])
feature = np.array(["Price", "Stock"])



In [5]:
menu[(name == "Chocolate") | (name == "strawberry")]

array([[ 2, 10],
       [ 4, 10]])

In [6]:
menu[name == "Chocolate", feature == "Stock"]

array([10])

In [7]:
def menu_data(name_data, feature_data):
    return menu[name == name_data, feature == feature_data]

In [8]:
menu_data("Apple","Stock")

array([10])

In [34]:
money = 0
#일반적 정수
def buy_icecream(menu, icecream,money):
    money += menu_data(icecream,"Price")
    menu[name==icecream, feature=="Stock"] -= 1
    return money

In [33]:
money = buy_icecream(menu, "Apple", money)
menu,money

(array([[ 2, 10],
        [ 3,  4],
        [ 4, 10],
        [ 5, 10],
        [ 6,  1]]),
 array([79]))

메뉴추가

In [11]:
name = np.append(name, ["Banana"])

In [12]:
name

array(['Chocolate', 'Vanila', 'strawberry', 'Orange', 'Apple', 'Banana'],
      dtype='<U10')

In [13]:
menu = np.append(menu, np.array([[7,10]]), axis=0)

In [14]:
menu

array([[ 2, 10],
       [ 3, 10],
       [ 4, 10],
       [ 5, 10],
       [ 6,  9],
       [ 7, 10]])

In [15]:
money = buy_icecream(menu,"Banana",money)
menu, money


(array([[ 2, 10],
        [ 3, 10],
        [ 4, 10],
        [ 5, 10],
        [ 6,  9],
        [ 7,  9]]),
 array([13]))

메뉴없애기

In [16]:
truth = name != "Banana"

In [17]:
name = name[truth]
menu = menu[truth]

In [18]:
name,menu

(array(['Chocolate', 'Vanila', 'strawberry', 'Orange', 'Apple'],
       dtype='<U10'),
 array([[ 2, 10],
        [ 3, 10],
        [ 4, 10],
        [ 5, 10],
        [ 6,  9]]))

재고 확인 후 리필

In [25]:
money = buy_icecream(menu, "Vanila", money)
stock = menu[:, feature=="Stock"]
stock

array([[10],
       [ 4],
       [10],
       [10],
       [ 9]])

In [20]:
stock > 5

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [86]:
stock = np.where(stock>5, stock, 10)
stock

array([[10],
       [10],
       [10],
       [10],
       [ 9]])