## Numpy 기초

# 1. Numpy 사용법

In [13]:
import numpy as np
# numpy 사용

In [14]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [15]:
data2 = [1,2,3,4,5,6,7]
data2

[1, 2, 3, 4, 5, 6, 7]

In [16]:
#numpy를 이용하여 array정의하기
# 1. 위에서만든python list 이용 
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [17]:
#array의 크기확인 
arr1.shape

(5,)

In [18]:
#python list 를  바로넣어 array 정의
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [19]:
#array 자료형 확인
arr2.dtype

dtype('int64')

In [20]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
arr4.shape

(4, 3)

numpy shape
-array 크기확인
-(5,) = 1차원의 데이터, 총 5 라는 크기.
-(4,3) = 2차원데이터 , (4* 3)라는 크기.

In [22]:
arr4.dtype

dtype('int64')

In [23]:
arr5 = np.array([1,2,3.5,4,5])
arr5.dtype

dtype('float64')

numpy 자료형
arr.4 의 자료형 = int 64
arr.5 의 자료형 = float 64
numpy 자료형 
    부호가 있는 정수 int(8, 16, 32, 64)
    부호가 없는 정수 uint(8 ,16, 32, 54)
    실수 float(16, 32, 64, 128)
    복소수 complex(64, 128, 256)
    불리언 bool
    문자열 string_
    파이썬 오프젝트 object
    유니코드 unicode_

In [31]:
np.zeros(10),np.zeros((3,5)),np.ones(9),np.ones((2,10)),np.arange(10),np.arange(3,10)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3, 4, 5, 6, 7, 8, 9]))

In [25]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
https://doorbw.tistory.com/171