In [6]:
import numpy as np
x = np.arange(1,11)

In [7]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
y = np.arange(10, 0 , -1)
y

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [33]:
cond = np.array([True, True, True, True, False, False, False, False, False, False])

In [36]:
def true_false_array(cond, x, y):
    result = [] 
    for index, value in enumerate(cond):
        if value == True:
            result.append(x[index])
        else:
            result.append(y[index])
    return result

In [37]:
result = true_false_array(cond, x, y)
result

[1, 2, 3, 4, 6, 5, 4, 3, 2, 1]

In [38]:
result = np.where(cond, x, y)
result

array([1, 2, 3, 4, 6, 5, 4, 3, 2, 1])

In [43]:
rand_arr = np.random.randn(4,4)
rand_arr
#랜덤

array([[-1.12296225, -1.16101734, -0.78154047,  0.19493349],
       [ 0.08949805, -0.00859945, -1.60413852, -0.35882278],
       [-0.84846937, -1.12485867, -1.02915999,  1.46613646],
       [-0.13766316,  0.57970514,  0.90076497,  0.39903924]])

In [53]:
truth_table = rand_arr >= 0

In [54]:
truth_table

array([[False, False, False,  True],
       [ True, False, False, False],
       [False, False, False,  True],
       [False,  True,  True,  True]])

In [56]:
np.where(truth_table, 2 , -2)

array([[-2, -2, -2,  2],
       [ 2, -2, -2, -2],
       [-2, -2, -2,  2],
       [-2,  2,  2,  2]])

In [58]:
x = np.arange(1,17).reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
np.sum(x)

136

In [60]:
np.mean(x)

8.5

In [64]:
np.min(x)

1

In [65]:
np.median(x)

8.5

In [67]:
np.std(x)

4.6097722286464435